home/urls.py
from django.urls import path

from home.views import (
    AboutView,
    DashboardView,
    closeAllValvesView
)

app_name = "home"
urlpatterns = [
    path("", DashboardView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("closeallvalves/", closeAllValvesView, name="closeallvalves"),
]

irrigation/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("home.urls")),
    path("admin/", admin.site.urls),
    path("programs/", include("programs.urls")),
    path("schedules/", include("schedules.urls")),
]

home/models.py
from django.db import models


class Settings(models.Model):
    weather_api_key = models.CharField(max_length=64)
    site_latitude = models.FloatField()
    site_longitude = models.FloatField()
    site_elevation = models.FloatField()
    tzcenter_longitude = models.FloatField()
    
    mqtt_user = models.CharField(max_length=32)
    mqtt_password = models.CharField(max_length=32)

    tank_capacity = models.FloatField()
    water_quota = models.FloatField()


class Log(models.Model):
    datetime = models.DateTimeField()
    message = models.CharField(max_length=128)

home/views.py
"""Main views for the site"""

from django.shortcuts import render, HttpResponseRedirect
from django.views import View
from django.utils import timezone
from django.urls import reverse

from schedules.models import ScheduledRun, Action
from home.models import Log
from controllers.models import Channel
from irrigation import mqtt


class DashboardView(View):
    template_name = "home/home.html"

    def get(self, request, *args, **kwargs):
        now = timezone.datetime(2019, 10, 1)
        current_weather = "Sunny"
        current_temperature = 28
        tank_level = 65
        timespan = timezone.timedelta(hours=24)
        upcoming_schedules = ScheduledRun.objects.filter(
            start__gte=now, start__lt=now + timespan)
        upcoming_actions = Action.objects.filter(
            datetime__gte=now, datetime__lt=now + timespan)
        last_logs = Log.objects.order_by("-datetime")[:5]

        context = {
            "pagetitle": "Home",
            "current_weather": current_weather,
            "current_temperature": current_temperature,
            "tank_level": tank_level,
            "schedule_list": upcoming_schedules,
            "action_list": upcoming_actions,
            "log_list": last_logs,
        }
        return render(request, self.template_name, context)


class AboutView(View):
    template_name = "home/about.html"

    def get(self, request, *args, **kwargs):
        "GET request handler"
        context = {
            "pagetitle": "About"
        }
        return render(request, self.template_name, context)

def closeAllValvesView(request):
    channels = Channel.objects.all()
    for channel in channels:
        topic = "/commands/" + channel.topic
        data = "c"
        mqtt.client.publish(topic, data, qos=1)

    return HttpResponseRedirect(reverse("home:home"))

home/templates/home/about.html
{% extends 'base.html' %}

{% block content %}

<h2>Plant waterinator 3000</h2>

<p> This application is released under 
    <a href="https://opensource.org/licenses/MIT">The MIT License</a></p>

<p> Copyright &copy; 2019, Levente Révész</p>

<p> Permission is hereby granted, free of charge, to any person obtaining a 
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the 
    Software is furnished to do so, subject to the following conditions: </p>

<p> The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software. </p>

<p> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
    THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
    DEALINGS IN THE SOFTWARE.
</p>

{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}

{% block content %}

<h2>Weather</h2>
{{ current_weather }}, {{ current_temperature }} °C

<h2>Tank level</h2>
{{ tank_level }}%

<p>
    <a class="w3-button w3-red" href="{% url 'home:closeallvalves' %}">
    Stop all valves
    </a>
</p>

<h2>Upcoming irrigation events</h2>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
    google.charts.load('current', { 'packages': ['timeline'] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var container = document.getElementById('timeline');
        var chart = new google.visualization.Timeline(container);
        var dataTable = new google.visualization.DataTable();

        dataTable.addColumn({ type: 'string', id: 'Zone' });
        dataTable.addColumn({ type: 'string', id: 'Program'});
        dataTable.addColumn({ type: 'date', id: 'Start' });
        dataTable.addColumn({ type: 'date', id: 'End' });
        dataTable.addRows([
            //{% for schedule in schedule_list %}
            ['{{schedule.request.zone.name}}', '{{schedule.request.program.name}}', new Date("{{schedule.start.isoformat}}"), new Date("{{schedule.end.isoformat}}")],
            //{% endfor %}
        ]);
        var options = {
            timeline: { groupByRowLabel: false, height: 300 }
        };

        chart.draw(dataTable, options);
    }
</script>
<div>
    <div id="timeline", style="height:300px;"></div>

</div>

<table class="w3-table w3-striped w3-border w3-margin-top">
    <thead>
        <tr class="w3-light-grey">
            <th>zone</th>
            <th>program</th>
            <th>start</th>
            <th>duration</th>
        </tr>
    </thead>
    <tbody>
        {% for schedule in schedule_list %}
        <tr>
            <td>{{ schedule.request.zone.name }}</td>
            <td>{{ schedule.request.program.name }}</td>
            <td>{{ schedule.start.isoformat }}</td>
            <td>{{ schedule.duration }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<h2>Upcoming actions</h2>
<table class="w3-table w3-striped w3-border w3-margin-top">
    <thead>
        <tr class="w3-light-grey">
            <th>zone</th>
            <th>channel</th>
            <th>start</th>
            <th>command</th>
        </tr>
    </thead>
    <tbody>
        {% for action in action_list %}
        <tr>
            <td>{{ action.schedule.request.zone.name }}</td>
            <td>{{ action.channel.name }}</td>
            <td>{{ action.datetime.isoformat }}</td>
            <td>{{ action.commandname }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>


<h2>Log</h2>
<table class="w3-table w3-striped w3-border w3-margin-top">
    <thead>
        <tr class="w3-light-grey">
            <th>time</th>
            <th>entry</th>
        </tr>
    </thead>
    <tbody>
        {% for log in log_list %}
        <tr>
            <td>{{ log.datetime }}</td>
            <td>{{ log.message }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

home/templates/home/test.html
{% extends 'base.html' %}

{% block content %}

<h2>{% lorem 2 w random %}</h2>
{% lorem 3 p random%}

<h2>{% lorem 2 w random %}</h2>
{% lorem 6 p random%}

<h2>{% lorem 2 w random %}</h2>
{% lorem 4 p random%}

{% endblock %}