home/urls.py
from django.urls import path

from home.views import (
    AboutView,
    DashboardView,
    closeAllValvesView
)

app_name = "home"
urlpatterns = [
    path("", DashboardView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("closeallvalves/", closeAllValvesView, name="closeallvalves"),
]

irrigation/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("home.urls")),
    path("admin/", admin.site.urls),
    path("programs/", include("programs.urls")),
    path("schedules/", include("schedules.urls")),
]

programs/urls.py
from django.urls import path

from programs.views import (
    ProgramCreateView,
    ProgramDeleteView,
    ProgramDetailView,
    ProgramListView,
    ProgramsHomeView,
    ProgramUpdateView,
    RunOnceProgramCreateView,
    PeriodicProgramCreateView,
    WeeklyProgramCreateView,
)

app_name = "programs"
urlpatterns = [
    path("", ProgramsHomeView.as_view(), name="home"),
    path("list/", ProgramListView.as_view(), name="list"),
    path("create/", ProgramCreateView.as_view(), name="create"),
    path("create/run-once/", RunOnceProgramCreateView.as_view(), name="create-run-once"),
    path("create/periodic/", PeriodicProgramCreateView.as_view(), name="create-periodic"),
    path("create/weekly/", WeeklyProgramCreateView.as_view(), name="create-weekly"),
    path("<int:id>/", ProgramDetailView.as_view(), name="detail"),
    path("<int:id>/update/", ProgramUpdateView.as_view(), name="update"),
    path("<int:id>/delete/", ProgramDeleteView.as_view(), name="delete"),
]

schedules/urls.py
from django.urls import path

from schedules.views import ScheduledRunListView

app_name = "schedules"
urlpatterns = [
    path("", ScheduledRunListView.as_view(), name="overview"),
]

templates/base.1.html
<!DOCTYPE html>

<html lang="en" dir="ltr">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charset="utf-8" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'w3.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'w3-theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'w3-custom.css' %}">

</head>

<body>
    <!-- Header -->
    <header class="w3-bar w3-theme-d3">
        <div class="w3-content">
            <div class="w3-bar-item w3-xxlarge w3-mono w3-padding-16">
                IrrigationProject
            </div>
            <div class="w3-bar-item w3-bar w3-small w3-right navbar-margin-top">
                {% include 'navbar.html' %}
            </div>
        </div>
    </header>

    <div class="w3-bar w3-theme">
        <div class="w3-container w3-content">
            <div class="">
                <h1 class="w3-xlarge">{{ pagetitle }}</h1>
            </div>
        </div>
    </div>

    <div class="w3-container">
        <div class="w3-container w3-content">
            {% block content %}
            Main content of the page
            ...
            {% endblock %}
        </div>
    </div>

</body>

</html>

templates/base.html
<!DOCTYPE html>

<html lang="en" dir="ltr">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charset="utf-8" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'w3.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'w3-theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'w3-custom.css' %}">

</head>

<body class="w3-light-gray">

    <div class="w3-content w3-white">
        <div class="w3-cell-row">


            <div class="w3-cell w3-bar-block w3-theme-grey w3-hide-small sidebar">
                <header class="w3-container w3-bar w3-theme-d3 headerheight">
                    <div class="w3-bar-item w3-xlarge w3-mono">
                        Irrigation
                    </div>
                </header>
                <div class="w3-container w3-theme-grey">
                    <div class="w3-padding-32 w3-center">
                        v0.1
                    </div>
                </div>
                <div class="w3-container w3-theme-dark-grey w3-padding w3-small w3-bold">
                    Navigation
                </div>
                <div class="w3-small w3-theme-grey">
                    {% include 'navbar.html' %}
                </div>
            </div>


            <div class="w3-cell">
                <header class="w3-theme-d3 headerheight">
                    <div class="w3-bar">
                        <div class="w3-bar-item">
                            <h1 style="font-size: 18pt; margin: 0;"> > {{ pagetitle }}</h1>
                        </div>
                    </div>
                </header>

                <div class="w3-container w3-content w3-padding">
                    {% block content %}
                    Main content of the page
                    ...
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>

</body>

</html>

templates/navbar.html
<nav>
    <a href="{% url 'home:home'     %}" class="w3-bar-item w3-button w3-padding w3-hover-theme-grey"><b>HOME</b></a>
    <a href="{% url 'programs:home' %}" class="w3-bar-item w3-button w3-padding w3-hover-theme-grey"><b>PROGRAMS</b></a>
    <a href="{% url 'schedules:overview' %}" class="w3-bar-item w3-button w3-padding w3-hover-theme-grey"><b>SCHEDULE</b></a>
    <a href="#" class="w3-bar-item w3-button w3-padding w3-hover-theme-grey"><b>STATS</b></a>
    <a href="#" class="w3-bar-item w3-button w3-padding w3-hover-theme-grey"><b>SETTINGS</b></a>
    <a href="{% url 'home:about'    %}" class="w3-bar-item w3-button w3-padding w3-hover-theme-grey"><b>ABOUT</b></a>
</nav>