home/urls.py
from django.urls import path

from home.views import (
    AboutView,
    DashboardView,
    closeAllValvesView
)

app_name = "home"
urlpatterns = [
    path("", DashboardView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("closeallvalves/", closeAllValvesView, name="closeallvalves"),
]

irrigation/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("home.urls")),
    path("admin/", admin.site.urls),
    path("programs/", include("programs.urls")),
    path("schedules/", include("schedules.urls")),
]

programs/urls.py
from django.urls import path

from programs.views import (
    ProgramCreateView,
    ProgramDeleteView,
    ProgramDetailView,
    ProgramListView,
    ProgramsHomeView,
    ProgramUpdateView,
    RunOnceProgramCreateView,
    PeriodicProgramCreateView,
    WeeklyProgramCreateView,
)

app_name = "programs"
urlpatterns = [
    path("", ProgramsHomeView.as_view(), name="home"),
    path("list/", ProgramListView.as_view(), name="list"),
    path("create/", ProgramCreateView.as_view(), name="create"),
    path("create/run-once/", RunOnceProgramCreateView.as_view(), name="create-run-once"),
    path("create/periodic/", PeriodicProgramCreateView.as_view(), name="create-periodic"),
    path("create/weekly/", WeeklyProgramCreateView.as_view(), name="create-weekly"),
    path("<int:id>/", ProgramDetailView.as_view(), name="detail"),
    path("<int:id>/update/", ProgramUpdateView.as_view(), name="update"),
    path("<int:id>/delete/", ProgramDeleteView.as_view(), name="delete"),
]

schedules/urls.py
from django.urls import path

from schedules.views import ScheduledRunListView

app_name = "schedules"
urlpatterns = [
    path("", ScheduledRunListView.as_view(), name="overview"),
]

home/models.py
from django.db import models


class Settings(models.Model):
    weather_api_key = models.CharField(max_length=64)
    site_latitude = models.FloatField()
    site_longitude = models.FloatField()
    site_elevation = models.FloatField()
    tzcenter_longitude = models.FloatField()
    
    mqtt_user = models.CharField(max_length=32)
    mqtt_password = models.CharField(max_length=32)

    tank_capacity = models.FloatField()
    water_quota = models.FloatField()


class Log(models.Model):
    datetime = models.DateTimeField()
    message = models.CharField(max_length=128)

programs/forms.py
"""program forms"""

from django import forms

from .models import Program


class ProgramModelForm(forms.ModelForm):
    "Default Model Form"
    class Meta:
        model = Program
        fields = [
            "name",
            "description",
            "program_type",
            "date_start",
            "date_end",
            "days_of_week",
            "time_start",
            "duration",
            "period",
            "priority",
            "enabled",
        ]

    def __init__(self, *args, **kwargs):
        "Update field definitions with custom attributes"
        super().__init__(*args, **kwargs)
        self.fields["name"].widget.attrs.update({
            "class": "w3-input w3-border",
            "style": "width:20em; display:inline-block;"
        })
        self.fields["description"].widget.attrs.update(
            {"class": "w3-input w3-border", "rows": 3})
        self.fields["program_type"].widget.attrs.update({
            "class": 'w3-select w3-border',
            "style": "width:8em;"
        })
        self.fields["date_start"].widget.attrs.update({
            "class": "w3-input w3-border",
            "style": "width:15em; display:inline-block;",
            "placeholder": "yyyy-mm-dd"
        })
        self.fields["date_end"].widget.attrs.update({
            "class": "w3-input w3-border",
            "style": "width:15em; display:inline-block;",
            "placeholder": "yyyy-mm-dd"
        })
        self.fields["time_start"].widget.attrs.update({
            "class": "w3-input w3-border",
            "style": "width:15em; display:inline-block;",
            "placeholder": "(hh:)mm:ss"
        })
        self.fields["duration"].widget.attrs.update({
            "class": "w3-input w3-border",
            "style": "width:15em; display:inline-block;",
            "placeholder": "(hh:)mm:ss"
        })
        self.fields["period"].widget.attrs.update({
            "class": "w3-input w3-border",
            "style": "width:15em; display:inline-block;",
            "placeholder": "(days) hh:mm(:ss)"
        })
        self.fields["priority"].widget.attrs.update({
            "class": "w3-input w3-border",
            "style": "width:4em; display:inline-block;"
        })
        self.fields["enabled"].widget.attrs.update(
            {"class": "w3-check"})

    def clean_time_start(self):
        "Raise error if field is required but empty"
        time_start = self.cleaned_data.get("time_start")
        if self.cleaned_data.get("program_type") in ("weekly",):
            if time_start is None:
                raise forms.ValidationError(
                    "This field is required for the selected program type.")
        return time_start

    def clean_duration(self):
        "Raise error if field is required but empty"
        duration = self.cleaned_data.get("duration")
        if self.cleaned_data.get("program_type") in ("run-once", "periodic", "weekly"):
            if duration is None:
                raise forms.ValidationError(
                    "This field is required for the selected program type.")
        return duration

    def clean_period(self):
        "Raise error if field is required but empty"
        period = self.cleaned_data.get("period")
        if self.cleaned_data.get("program_type") in ("periodic",):
            if period is None:
                raise forms.ValidationError(
                    "This field is required for the selected program type.")
        return period


class ProgramFormMixin(object):
    "Set common attributes for all program types"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            "class": "w3-input"})
        self.fields['description'].widget.attrs.update({
            "class": "w3-input",
            "rows": 2})
        self.fields['date_start'].required = True
        self.fields['date_start'].widget.attrs.update({
            "class": "w3-input w3-border",
            "placeholder": "yyyy-mm-dd",
            "style": "max-width: 10em"})
        self.fields['time_start'].required = True
        self.fields['time_start'].widget.attrs.update({
            "class": "w3-input w3-border",
            "placeholder": "(hh:)mm:ss",
            "style": "max-width: 10em"})
        self.fields['duration'].widget.attrs.update({
            "class": "w3-input w3-border",
            "placeholder": "(d) (hh:)mm:ss",
            "style": "max-width: 10em"})
        self.fields['priority'].required = True
        self.fields['priority'].widget.attrs.update({
            "class": "w3-input w3-border",
            "type": "number", "min": "1", "max": "10",
            "style": "max-width:4em"})
        self.fields['enabled'].widget.attrs.update({
            "class": "w3-check"})


class RunOnceProgramModelForm(ProgramFormMixin, forms.ModelForm):
    "Run-Once Program Model Form"
    program_type = forms.ChoiceField(
        choices=Program.PROGRAM_TYPES,
        widget=forms.HiddenInput(),
        initial="run-once",
    )

    class Meta:
        model = Program
        fields = [
            "name", "description", "program_type", "date_start", "time_start",
            "duration", "priority", "enabled"
        ]
        widgets = {
            "description": forms.Textarea(),
            "program_type": forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super().__init__(*args, **kwargs)
        self.fields['program_type'].initial = "run-once"


class PeriodicProgramModelForm(ProgramFormMixin, forms.ModelForm):
    "Periodic Program Model Form"

    class Meta:
        model = Program
        fields = [
            "name", "description", "program_type", "date_start", "date_end",
            "time_start", "duration", "period", "priority", "enabled"
        ]
        widgets = {
            "description": forms.Textarea(),
            "program_type": forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super().__init__(*args, **kwargs)
        self.fields['program_type'].initial = "periodic"
        self.fields['date_end'].widget.attrs.update({
            "class": "w3-input w3-border",
            "placeholder": "yyyy-mm-dd",
            "style": "max-width: 10em"})
        self.fields['period'].required = True
        self.fields['period'].widget.attrs.update({
            "class": "w3-input w3-border",
            "placeholder": "days",
            "style": "max-width: 10em"})


class WeeklyProgramModelForm(ProgramFormMixin, forms.ModelForm):
    "Weekly Program Model Form"
    days_of_week = forms.MultipleChoiceField(
        choices=Program.DAYS_OF_WEEK,
        widget=forms.CheckboxSelectMultiple(),
        required=False
    )

    class Meta:
        model = Program
        fields = [
            "name", "description", "program_type", "date_start", "date_end",
            "days_of_week", "time_start", "duration", "priority", "enabled"
        ]
        widgets = {
            "description": forms.Textarea(),
            "program_type": forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super().__init__(*args, **kwargs)
        self.fields['program_type'].initial = "weekly"
        self.fields['date_end'].widget.attrs.update({
            "class": "w3-input w3-border",
            "placeholder": "yyyy-mm-dd",
            "style": "max-width: 10em"})
        self.fields['days_of_week'].widget.attrs.update({
            "class": "w3-check"})

    def clean_days_of_week(self):
        "Transforms the List of selected days to a String"
        days_of_week = self.cleaned_data.get("days_of_week")
        days_of_week_str = "".join(days_of_week)
        return days_of_week_str

home/views.py
"""Main views for the site"""

from django.shortcuts import render, HttpResponseRedirect
from django.views import View
from django.utils import timezone
from django.urls import reverse

from schedules.models import ScheduledRun, Action
from home.models import Log
from controllers.models import Channel
from irrigation import mqtt


class DashboardView(View):
    template_name = "home/home.html"

    def get(self, request, *args, **kwargs):
        now = timezone.datetime(2019, 10, 1)
        current_weather = "Sunny"
        current_temperature = 28
        tank_level = 65
        timespan = timezone.timedelta(hours=24)
        upcoming_schedules = ScheduledRun.objects.filter(
            start__gte=now, start__lt=now + timespan)
        upcoming_actions = Action.objects.filter(
            datetime__gte=now, datetime__lt=now + timespan)
        last_logs = Log.objects.order_by("-datetime")[:5]

        context = {
            "pagetitle": "Home",
            "current_weather": current_weather,
            "current_temperature": current_temperature,
            "tank_level": tank_level,
            "schedule_list": upcoming_schedules,
            "action_list": upcoming_actions,
            "log_list": last_logs,
        }
        return render(request, self.template_name, context)


class AboutView(View):
    template_name = "home/about.html"

    def get(self, request, *args, **kwargs):
        "GET request handler"
        context = {
            "pagetitle": "About"
        }
        return render(request, self.template_name, context)

def closeAllValvesView(request):
    channels = Channel.objects.all()
    for channel in channels:
        topic = "/commands/" + channel.topic
        data = "c"
        mqtt.client.publish(topic, data, qos=1)

    return HttpResponseRedirect(reverse("home:home"))

programs/views.py
"""programs views"""

from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView
)

from .forms import (
    ProgramModelForm,
    RunOnceProgramModelForm,
    PeriodicProgramModelForm,
    WeeklyProgramModelForm,
)
from .models import Program

#pylint: disable=arguments-differ


class ProgramsHomeView(ListView):
    "General info about the programs"
    template_name = "programs/home.html"
    queryset = Program.objects.filter(enabled=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # additional context
        context["pagetitle"] = "Programs"
        return context


class ProgramListView(ListView):
    "Display the list of all Programs"
    template_name = "programs/list.html"
    queryset = Program.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # additional context
        context["pagetitle"] = "List of Programs"
        return context


class ProgramDetailView(DetailView):
    "Dispaly the details of Program given by id"
    template_name = "programs/detail.html"
    queryset = Program.objects.all()  # optional filter

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Program, id=id_)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # additional context
        context["pagetitle"] = "Program Details"
        return context


class ProgramCreateView(View):
    "Create a new program"
    template_name = "programs/create.html"

    def get(self, request, *args, **kwargs):
        "GET request handler"
        context = {
            "pagetitle": "Create New Program"
        }
        return render(request, self.template_name, context)


class ProgramUpdateView(UpdateView):
    "Update a program"
    #TODO switch on program type 
    template_name = "programs/create.html"
    form_class = ProgramModelForm

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Program, id=id_)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # additional context
        context["pagetitle"] = "Update Program"
        return context

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)


class ProgramDeleteView(DeleteView):
    "Create a new program"
    template_name = "programs/delete.html"

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Program, id=id_)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # additional context
        context["pagetitle"] = "Delete Program"
        return context

    def get_success_url(self):
        return reverse("programs:home")


class CreateViewMixin(object):
    "Create View methods common for all program types"

    def get_context_data(self, **kwargs):
        "Set additional key-value pairs"
        context = super().get_context_data(**kwargs)
        context["pagetitle"] = "Create New Program"
        return context

    def form_valid(self, form):
        "Validation method"
        print(form.cleaned_data)
        return super().form_valid(form)


class RunOnceProgramCreateView(CreateViewMixin, CreateView):
    "Create a new program"
    template_name = "programs/create_run-once.html"
    form_class = RunOnceProgramModelForm


class PeriodicProgramCreateView(CreateViewMixin, CreateView):
    "Create a new program"
    template_name = "programs/create_periodic.html"
    form_class = PeriodicProgramModelForm


class WeeklyProgramCreateView(CreateViewMixin, CreateView):
    "Create a new program"
    template_name = "programs/create_weekly.html"
    form_class = WeeklyProgramModelForm

programs/templates/programs/create.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'programs:create-run-once' %}" class="w3-button w3-round w3-light-grey w3-text-dark-grey w3-border w3-small w3-bold"> Run-Once </a>
<a href="{% url 'programs:create-periodic' %}" class="w3-button w3-round w3-light-grey w3-text-dark-grey w3-border w3-small w3-bold"> Periodic </a>
<a href="{% url 'programs:create-weekly' %}"   class="w3-button w3-round w3-light-grey w3-text-dark-grey w3-border w3-small w3-bold"> Weekly </a>

{% endblock %}

programs/templates/programs/create_base.html
{% extends 'base.html' %}

{% block content %}

<form action="." method="POST">{% csrf_token %}

    {{ form.non_field_errors }}
    {{ form.program_type.errors }}
    {{ form.program_type }}

    <div class="">
        <div class="w3-cell-row">
            <div class="w3-padding w3-cell w3-cell-top w3-mobile form-label">{{ form.name.label }}</div>
            <div class="w3-padding w3-cell w3-cell-top w3-mobile">{{ form.name.errors }}{{ form.name }}</div>
        </div>
        <div class="w3-cell-row">
            <div class="w3-padding w3-cell w3-cell-top w3-mobile form-label">{{ form.description.label }}</div>
            <div class="w3-padding w3-cell w3-cell-top w3-mobile">{{ form.description.errors }}{{ form.description }}</div>
        </div>
        <div class="w3-cell-row">
            <div class="w3-padding w3-cell w3-cell-top form-label">{{ form.date_start.label }}</div>
            <div class="w3-padding w3-cell w3-cell-top">{{ form.date_start.errors }}{{ form.date_start }}</div>
        </div>

        {% block extra_fields %}

        {% endblock %}

        <div class="w3-cell-row">
            <div class="w3-padding w3-cell w3-cell-top form-label">{{ form.duration.label }}</div>
            <div class="w3-padding w3-cell w3-cell-top">{{ form.duration.errors }}{{ form.duration }}</div>
        </div>
        <div class="w3-cell-row">
            <div class="w3-padding w3-cell w3-cell-top form-label">{{ form.priority.label }}</div>
            <div class="w3-padding w3-cell w3-cell-top">{{ form.priority.errors }}{{ form.priority }}</div>
        </div>
        <div class="w3-cell-row">
            <div class="w3-padding w3-cell w3-cell-top form-label">{{ form.enabled.label }}</div>
            <div class="w3-padding w3-cell w3-cell-top">{{ form.enabled.errors }}{{ form.enabled }}</div>
        </div>

    </div>
    <div class="w3-margin-top">
        <a href="{% url 'programs:home' %}" class="w3-button w3-round w3-light-grey w3-text-dark-grey w3-border w3-small w3-bold">CANCEL</a>
        <input type="submit" value="SAVE"
            class="w3-button w3-round w3-theme w3-border w3-border-theme w3-hover-border-gray w3-small w3-bold">
    </div>
</form>

{% endblock %}

programs/templates/programs/create_periodic.html
{% extends 'programs/create_base.html' %}

{% block extra_fields %}

<div class="w3-cell-row">
    <div class="w3-padding w3-cell w3-cell-top form-label">{{ form.date_end.label }}</div>
    <div class="w3-padding w3-cell w3-cell-top">{{ form.date_end.errors }}{{ form.date_end }}</div>
</div>
<div class="w3-cell-row">
    <div class="w3-padding w3-cell w3-cell-top form-label">{{ form.period.label }}</div>
    <div class="w3-padding w3-cell w3-cell-top">{{ form.period.errors }}{{ form.period }}</div>
</div>
<div class="w3-cell-row">
    <div class="w3-padding w3-cell w3-cell-top form-label">{{ form.time_start.label }}</div>
    <div class="w3-padding w3-cell w3-cell-top">{{ form.time_start.errors }}{{ form.time_start }}</div>
</div>

{% endblock %}

programs/templates/programs/create_run-once.html
{% extends 'programs/create_base.html' %}

{% block extra_fields %}

<div class="w3-cell-row">
    <div class="w3-padding w3-cell w3-cell-top form-label">{{ form.time_start.label }}</div>
    <div class="w3-padding w3-cell w3-cell-top">{{ form.time_start.errors }}{{ form.time_start }}</div>
</div>

{% endblock %}

programs/templates/programs/create_weekly.html
{% extends 'programs/create_base.html' %}

{% block extra_fields %}

<div class="w3-cell-row">
    <div class="w3-padding w3-cell w3-cell-top form-label">{{ form.date_end.label }}</div>
    <div class="w3-padding w3-cell w3-cell-top">{{ form.date_end.errors }}{{ form.date_end }}</div>
</div>
<div class="w3-cell-row">
    <div class="w3-padding w3-cell w3-cell-top w3-mobile form-label">{{ form.days_of_week.label }}</div>
    <div class="w3-padding w3-cell w3-cell-top w3-mobile">
        {{ form.days_of_week.errors }}
        <ul style="padding-left:0">
            {% for day in form.days_of_week %}
            <li style="display:inline">
                <span style="white-space:nowrap">
                    <span>{{ day.tag }}</span>
                    <label for="{{ day.id_for_label }}">{{ day.choice_label|upper|slice:":3" }}</label>
                </span>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
<div class="w3-cell-row">
    <div class="w3-padding w3-cell w3-cell-top form-label">{{ form.time_start.label }}</div>
    <div class="w3-padding w3-cell w3-cell-top">{{ form.time_start.errors }}{{ form.time_start }}</div>
</div>

{% endblock %}

programs/templates/programs/create_weekly.old.html
{% extends 'base.html' %}

{% block content %}

<form action="." method="POST">{% csrf_token %}

    {{ form.non_field_errors }}
    {{ form.program_type.errors }}
    {{ form.program_type }}

    {{ form.name.errors }}
    <p>{{ form.name.label }}: {{ form.name }}</p>

    {{ form.description.errors }}
    <p>{{ form.description.label }}: {{ form.description }}</p>

    {{ form.date_start.errors }}
    <p>{{ form.date_start.label }}: {{ form.date_start }}</p>

    {{ form.date_end.errors }}
    <p>{{ form.date_end.label }}: {{ form.date_end }}</p>

    {{ form.days_of_week.errors }}
    <p>
        {{ form.days_of_week.label }}:
        <ul style="padding-left:0">
            {% for day in form.days_of_week %}
            <li style="display:inline">
                <span style="white-space:nowrap">
                    <span>{{ day.tag }}</span>
                    <label for="{{ day.id_for_label }}">{{ day.choice_label|upper|slice:":3" }}</label>
                </span>
            </li>
            {% endfor %}
        </ul>
    </p>

    {{ form.time_start.errors }}
    <p>{{ form.time_start.label }}: {{ form.time_start }}</p>

    {{ form.duration.errors }}
    <p>{{ form.duration.label }}: {{ form.duration }}</p>

    {{ form.priority.errors }}
    <p>{{ form.priority.label }}: {{ form.priority }}</p>

    {{ form.enabled.errors }}
    <p>{{ form.enabled.label }}: {{ form.enabled }}</p>

    <a href="../" class="w3-button w3-round w3-light-grey w3-text-dark-grey w3-border w3-small w3-bold">CANCEL</a>
    <input type="submit" value="SAVE"
        class="w3-button w3-round w3-theme w3-border w3-border-theme w3-hover-border-gray w3-small w3-bold">
</form>

{% endblock %}

programs/templates/programs/delete.html
{% extends 'base.html' %}

{% block content %}

<form action="." method="POST">{% csrf_token %}
    <h2>Do you want to delete this program?</h2>
    <p>Instead of deleting it permanently, you can also disable the program.</p>
    <a href="../" class="w3-button w3-round w3-light-grey w3-text-dark-grey w3-border w3-small w3-bold">CANCEL</a>
    <input type="submit" value="DELETE" class="w3-button w3-round w3-red w3-border w3-border-red w3-hover-border-gray w3-small w3-bold">
</form>

{% endblock %}

programs/templates/programs/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="w3-container w3-padding w3-theme w3-margin-top">
    <h3 class="w3-bold">{{ object.name }}</h3>
    {{ object.description }}
</div>
    
    <table class="w3-table w3-striped w3-border">
        <tr>
        <th>type</th>
        <td>{{ object.program_type }}</td>
    </tr>
    <tr>
        <th>zones</th>
        <td>
            {% for zone in object.zones.all %}
                {{ zone.name }} <br>
            {% endfor %}
        </td>
    </tr>
    <tr>
        <th>start</th>
        <td>{{ object.date_start|date:"Y-m-d" }}</td>
    </tr>
    <tr>
        <th>end</th>
        <td>{{ object.date_end|date:"Y-m-d" }}</td>
    </tr>
    {% if object.program_type == "weekly" %}
    <tr>
        <th>days of week</th>
        <td>{{ object.days_of_week }}</td>
    </tr>
    {% endif %}
    {% if object.program_type == "periodic" %}
    <tr>
        <th>period</th>
        <td>{{ object.period }}</td>
    </tr>
    {% endif %}
    <tr>
        <th>time</th>
        <td>{{ object.time_start|time:"H:i" }}</td>
    </tr>
    <tr>
        <th>duration</th>
        <td>{{ object.duration }}</td>
    </tr>
    <tr>
        <th>weather adaptivity</th>
        <td>{{ object.adaptivity }}</td>
    </tr>
    <tr>
        <th>priority</th>
        <td>{{ object.priority }}</td>
    </tr>
    <tr>
        <th>enabled</th>
        <td><input type="checkbox" disabled
            {% if object.enabled %} checked {% endif %} ></td>
    </tr>
</table>

<div class="w3-bar w3-margin-top">
    <div class="w3-right">
        <a href="./update"
        class="w3-bar-item w3-button w3-margin-left w3-round w3-light-grey w3-text-dark-grey w3-border w3-small w3-bold">EDIT</a>
        <a href="./delete"
        class="w3-bar-item w3-button w3-margin-left w3-round w3-light-grey w3-text-dark-grey w3-border w3-small w3-bold">DELETE</a>
    </div>
</div>

{% endblock %}

programs/templates/programs/home.html
{% extends 'base.html' %}

{% block content %}


<h2>Enabled programs</h2>
<table class="w3-table w3-striped w3-border w3-margin-top">
    <thead>
        <tr class="w3-light-grey">
            <th>id</th>
            <th>name</th>
            <th class="w3-center">enabled</th>
            <th class="w3-center">details</th>
        </tr>
    </thead>
    {% for object in object_list %}
    <tr>
        <td>{{ object.id }}</td>
        <td>{{ object.name }}</td>
        <td class="w3-center"><input type="checkbox" disabled {% if object.enabled %} checked {% endif %}>
        </td>
        <td class="w3-center">
            <a class="w3-button w3-large w3-round" style="padding-bottom:0; padding-top:0;"
                href="{{ object.get_absolute_url }}">&#x1f4c4;</a></td>
    </tr>
    {% endfor %}
</table>

<div class="w3-bar w3-margin-top">
    <div class="w3-right">
        <a href="{% url 'programs:list' %}"
            class="w3-bar-item w3-button w3-margin-left w3-round w3-light-grey w3-text-dark-grey w3-border w3-small w3-bold">VIEW
            ALL</a>
        <a href="{% url 'programs:create' %}"
            class="w3-bar-item w3-button w3-margin-left w3-round w3-theme w3-border w3-small w3-bold">CREATE</a>
    </div>
</div>

{% endblock %}

programs/templates/programs/list.html
{% extends 'base.html' %}

{% block content %}

<table class="w3-table w3-striped w3-border w3-margin-top">
    <thead>
        <tr class="w3-light-grey">
            <th>name</th>
            <th>type</th>
            <th>time</th>
            <th>duration</th>
            <th class="w3-center">enabled</th>
            <th class="w3-center">details</th>
        </tr>
    </thead>
    {% for program in object_list %}
    <tr>
        <td>{{ program.name }}</td>
        <td>{{ program.program_type }}</td>
        <td>{{ program.time_start|time:"H:i"}}</td>
        <td>{{ program.duration }}</td>
        <td class="w3-center"><input type="checkbox" disabled {% if program.enabled %} checked {% endif %}>
        </td>
        <td class="w3-center">
            <a class="w3-button w3-large w3-round" style="padding-bottom:0; padding-top:0;"
                href="{{ program.get_absolute_url }}">&#x1f4c4;</a></td>
    </tr>
    {% endfor %}
</table>

<div class="w3-bar w3-margin-top">
    <div class="w3-right">
        <a href="{% url 'programs:create' %}"
            class="w3-bar-item w3-button w3-margin-left w3-round w3-theme w3-border w3-small w3-bold">CREATE</a>
    </div>
</div>


{% endblock %}

programs/templates/programs/overview.html
{% extends 'base.html' %}

{% block content %}
<h3>Active programs</h3>
<ul>
    <li>
        program 1
    </li>
    <li>
        program 2
    </li>
</ul>

{% url "programs:overview" %}
{% url "home:homepage" %}

{% endblock %}